source "https://rubygems.org"
ruby "~> 3.3"

gem "rails", "~> 7.2.0"
gem "puma", "~> 6.4"
gem "sqlite3", "~> 2.1"
gem "rack-cors", "~> 2.0"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.8"

group :development do
  gem "debug"
end

group :deploy do
  gem "capistrano", "~> 3.18", require: false
  gem "capistrano3-puma", "~> 6.0", require: false
  gem "capistrano-bundler", "~> 2.1", require: false
  gem "capistrano-rbenv", "~> 2.2", require: false
end
