PLUGINS = [
  # ── Free plugins (from macOS bundled catalog) ────────────────────────────
  { name: "Vital",           manufacturer: "Matt Tytel",         category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Spectral warping wavetable synthesizer with a powerful modulation system, 3 oscillators, and detailed visual feedback.",
    version: "1.5.5", tags: "synth,wavetable,polyphonic", website_url: "https://vital.audio", github_repo: nil },
  { name: "Surge XT",        manufacturer: "Surge Synth Team",  category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Open-source hybrid synthesizer with extensive modulation capabilities, 300+ factory patches, and multiple synthesis types.",
    version: "1.3.4", tags: "synth,hybrid,open-source", website_url: "https://surge-synthesizer.github.io", github_repo: "surge-synthesizer/surge" },
  { name: "Dexed",           manufacturer: "Digital Suburban",  category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "FM synthesizer modeled after the Yamaha DX7, fully compatible with original DX7 SysEx patch banks.",
    version: "0.9.6", tags: "FM,synth,vintage,open-source", website_url: "https://asb2m10.github.io/dexed/", github_repo: "asb2m10/dexed" },
  { name: "Odin 2",          manufacturer: "TheWaveWarden",     category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Semi-modular synthesizer with 3 oscillators offering wavetable, FM, PM, and PM-FM synthesis plus a flexible modulation matrix.",
    version: "2.3.4", tags: "synth,semi-modular,wavetable,open-source", website_url: "https://www.thewavewarden.com/odin2", github_repo: "TheWaveWarden/odin2" },
  { name: "OB-Xd",           manufacturer: "discoDSP",          category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Virtual analog synthesizer modeled after the Oberheim OB-X with 4-voice polyphony and classic warm analog sound.",
    version: "2.8", tags: "synth,analog,vintage,Oberheim", website_url: "https://www.discodsp.com/obxd/", github_repo: nil },
  { name: "TAL-NoiseMaker",  manufacturer: "Togu Audio Line",   category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Virtual analog synthesizer with 3 oscillators, 2 filters, built-in arpeggiator, and stereo chorus for classic electronic tones.",
    version: "4.0", tags: "synth,analog,arpeggiator", website_url: "https://tal-software.com/products/tal-noisemaker", github_repo: nil },
  { name: "Helm",            manufacturer: "Matt Tytel",         category: "instrument", formats: "AU,VST2,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Polyphonic synthesizer with multiple oscillator types, flexible routing, and a built-in effects rack.",
    version: "0.9.0", tags: "synth,polyphonic,open-source", website_url: "https://tytel.org/helm/", github_repo: "mtytel/helm" },
  { name: "TDR Nova",        manufacturer: "Tokyo Dawn Labs",    category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Parallel dynamic equalizer combining classic parametric EQ with transparent multiband dynamics — ideal for mixing and mastering.",
    version: "2.2.4", tags: "EQ,dynamics,mastering", website_url: "https://www.tokyodawn.net/tdr-nova/", github_repo: nil },
  { name: "TAL-Reverb-4",    manufacturer: "Togu Audio Line",   category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "High quality plate reverb with a beautiful vintage character, simple controls, and lush long tails.",
    version: "1.5", tags: "reverb,plate,vintage", website_url: "https://tal-software.com/products/tal-reverb", github_repo: nil },
  { name: "SPAN",            manufacturer: "Voxengo",            category: "effect",     formats: "AU,VST2,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Real-time FFT audio spectrum analyzer with adjustable display range, resolution, and multiple display modes.",
    version: "3.18", tags: "analyzer,spectrum,metering", website_url: "https://www.voxengo.com/product/span/", github_repo: nil },
  { name: "Limiter No6",     manufacturer: "Vladimir Nadezhdin", category: "effect",    formats: "VST2,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Multi-stage limiter with RMS compressor, high-frequency limiter, clipper, and true peak limiter.",
    version: "1.2", tags: "limiter,mastering,dynamics,compressor", website_url: "https://vladg.net/plugin/limiter-no6", github_repo: nil },
  { name: "Ozone Imager 2",  manufacturer: "iZotope",            category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Stereo imaging plugin for widening or narrowing the stereo field with Lissajous metering.",
    version: "2.00", tags: "stereo,imaging,mastering", website_url: "https://www.izotope.com/en/products/ozone-imager.html", github_repo: nil },
  { name: "DragonflyReverb", manufacturer: "Michael Willis",     category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Open-source collection of four reverb types — room, hall, early reflections, and plate.",
    version: "3.2.10", tags: "reverb,open-source,room,hall", website_url: "https://github.com/michaelwillis/dragonfly-reverb", github_repo: "michaelwillis/dragonfly-reverb" },
  { name: "MFreeFXBundle",   manufacturer: "MeldaProduction",   category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Collection of 37 free audio plugins covering EQ, dynamics, modulation, analysis, and more.",
    version: "16.12", tags: "bundle,EQ,dynamics,modulation", website_url: "https://www.meldaproduction.com/MFreeFXBundle", github_repo: nil },
  { name: "TAL-Chorus-LX",  manufacturer: "Togu Audio Line",   category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: true,  price_usd: nil,
    description: "Emulation of the Roland Juno-60 chorus effect — adds the iconic lush, warm stereo spread to any signal.",
    version: "2.1", tags: "chorus,vintage,Roland,stereo", website_url: "https://tal-software.com/products/tal-chorus-lx", github_repo: nil },

  # ── Paid plugins ─────────────────────────────────────────────────────────
  { name: "Serum",           manufacturer: "Xfer Records",       category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: false, price_usd: 189.00,
    description: "The most popular wavetable synthesizer. Drag-and-drop wavetable editing with a visual workflow.",
    version: "1.36", tags: "synth,wavetable,lead,bass", website_url: "https://xferrecords.com/products/serum", github_repo: nil },
  { name: "Guitar Rig 7",   manufacturer: "Native Instruments", category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: false, price_usd: 299.00,
    description: "The ultimate amp and effects rack. 17 guitar amps, 27 cabinets, and 54 effects in one plugin.",
    version: "7.1.0", tags: "guitar,amp,effects,NI", website_url: "https://www.native-instruments.com/en/products/komplete/guitar/guitar-rig-7-pro/", github_repo: nil },
  { name: "Massive X",      manufacturer: "Native Instruments", category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: false, price_usd: 149.00,
    description: "Next evolution of Massive. Phase modulation, formant filters, and dual oscillator routing.",
    version: "1.5.3", tags: "synth,wavetable,massive,NI", website_url: "https://www.native-instruments.com/en/products/komplete/synths/massive-x/", github_repo: nil },
  { name: "FabFilter Pro-Q 3", manufacturer: "FabFilter",       category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: false, price_usd: 179.00,
    description: "Professional mastering EQ with dynamic EQ modes, linear phase, and a natural phase mode.",
    version: "3.22", tags: "eq,mastering,dynamics", website_url: "https://www.fabfilter.com/products/pro-q-3-equalizer-plug-in", github_repo: nil },
  { name: "Valhalla VintageVerb", manufacturer: "Valhalla DSP", category: "effect",     formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: false, price_usd: 50.00,
    description: "Classic hardware reverb algorithms from the 1970s–1980s. 17 algorithms, minimal CPU.",
    version: "3.0.3", tags: "reverb,vintage,hardware-emulation", website_url: "https://valhalladsp.com/shop/reverb/valhalla-vintage-verb/", github_repo: nil },
  { name: "Phase Plant",    manufacturer: "Kilohearts",          category: "instrument", formats: "AU,VST3",
    plugin_type: "VST 3",    is_free: false, price_usd: 99.00,
    description: "Modular semi-modular synth. Mix and match synthesis techniques in a single instrument.",
    version: "2.1.1", tags: "synth,modular,semi-modular", website_url: "https://kilohearts.com/products/phase_plant", github_repo: nil },
  { name: "Kontakt 7",      manufacturer: "Native Instruments", category: "instrument", formats: "AU,VST3",
    plugin_type: "Audio Unit", is_free: false, price_usd: 399.00,
    description: "The industry-standard sampler. 65 GB library, hundreds of third-party instruments.",
    version: "7.10", tags: "sampler,NI,orchestral,industry-standard", website_url: "https://www.native-instruments.com/en/products/komplete/samplers/kontakt-7/", github_repo: nil },
].freeze

SERUM_PRESETS = [
  { name: "Supersaw Anthem",  author: "AudioBunny", genre: "Trance",
    description: "Thick detuned supersaw stack for epic trance anthems. Wide stereo spread with subtle LFO.",
    tags: "supersaw,trance,pad,wide,anthem", file_extension: "fxp" },
  { name: "Deep Sub Bass",    author: "AudioBunny", genre: "Bass",
    description: "Punchy 808-style sub bass with gentle saturation and sidechain-ready envelope.",
    tags: "sub,bass,808,punchy", file_extension: "fxp" },
  { name: "Pluck Garden",     author: "AudioBunny", genre: "Ambient",
    description: "Delicate pluck with long reverb tail. Perfect for lo-fi and ambient productions.",
    tags: "pluck,ambient,lofi,reverb", file_extension: "fxp" },
  { name: "Rave Chord Stack", author: "AudioBunny", genre: "Trance",
    description: "Classic rave chord stab with unison detune and quick envelope for hard trance.",
    tags: "chord,rave,trance,stab", file_extension: "fxp" },
  { name: "Neuro Wobble",     author: "AudioBunny", genre: "Dubstep",
    description: "Aggressive neuro bass with LFO-modulated filter and distortion chain.",
    tags: "neuro,wobble,dubstep,bass,aggressive", file_extension: "fxp" },
  { name: "Lush Pad",         author: "AudioBunny", genre: "Ambient",
    description: "Evolving pad with slow filter sweep and chorus. Fills the stereo field beautifully.",
    tags: "pad,lush,evolving,ambient,slow", file_extension: "fxp" },
  { name: "Techno Seq",       author: "AudioBunny", genre: "Techno",
    description: "Acidic sequence synth with fast envelope and drive. Works great at 130–145 BPM.",
    tags: "techno,acid,sequence,arp", file_extension: "fxp" },
  { name: "FX Riser",         author: "AudioBunny", genre: "FX",
    description: "Upward sweep with pitch and filter automation baked into the modulation matrix.",
    tags: "fx,riser,sweep,transition", file_extension: "fxp" },
  { name: "Dirty Lead",       author: "AudioBunny", genre: "Rock",
    description: "Hard clipped, distorted lead with feedback saturation and slight pitch wobble.",
    tags: "lead,rock,dirty,distorted", file_extension: "fxp" },
  { name: "Crystal Keys",     author: "AudioBunny", genre: "Pop",
    description: "Bright, glassy keys patch. Clean and sparkly, sits perfectly in the high mids.",
    tags: "keys,pop,bright,glassy,clean", file_extension: "fxp" },
].freeze

GUITAR_RIG_PRESETS = [
  { name: "Smooth Jazz Clean", author: "AudioBunny", genre: "Jazz",
    description: "Warm Fender-style clean with gentle chorus and spring reverb. Great for jazz chords.",
    tags: "clean,jazz,warm,chorus,fender", file_extension: "ngrr" },
  { name: "Texas Crunch",      author: "AudioBunny", genre: "Blues",
    description: "Texas blues crunch with tube compression and a hint of spring reverb.",
    tags: "crunch,blues,texas,tube,spring", file_extension: "ngrr" },
  { name: "Modern Metal",      author: "AudioBunny", genre: "Metal",
    description: "High-gain modern metal with tight low end and scooped mids. Drop-tune ready.",
    tags: "metal,high-gain,modern,tight", file_extension: "ngrr" },
  { name: "Stoner Fuzz",       author: "AudioBunny", genre: "Rock",
    description: "Thick vintage fuzz for stoner and doom riffs. Lots of sustain and warmth.",
    tags: "fuzz,stoner,doom,vintage,sustain", file_extension: "ngrr" },
  { name: "Ambient Space",     author: "AudioBunny", genre: "Ambient",
    description: "Clean with heavy reverb and delay. Transforms any chord into a soundscape.",
    tags: "ambient,reverb,delay,clean,atmospheric", file_extension: "ngrr" },
  { name: "Classic Rock Lead", author: "AudioBunny", genre: "Rock",
    description: "Plexi-style crunch with tube screamer in front. Marshall-in-a-box tone.",
    tags: "classic-rock,lead,plexi,marshall,crunch", file_extension: "ngrr" },
  { name: "Death Metal",       author: "AudioBunny", genre: "Metal",
    description: "Extreme gain Rectifier-style tone. Crushing palm mutes, razor-sharp leads.",
    tags: "death-metal,extreme,rectifier,palm-mute", file_extension: "ngrr" },
  { name: "Blues Sustain",     author: "AudioBunny", genre: "Blues",
    description: "Medium overdrive with natural compression that makes leads sing with sustain.",
    tags: "blues,sustain,overdrive,natural", file_extension: "ngrr" },
].freeze

puts "Seeding plugins..."
Plugin.destroy_all
Preset.destroy_all

plugin_records = {}
PLUGINS.each do |attrs|
  p = Plugin.create!(attrs)
  plugin_records[p.name] = p
end
puts "  #{Plugin.count} plugins created."

puts "Seeding presets..."
serum      = plugin_records["Serum"]
guitar_rig = plugin_records["Guitar Rig 7"]

SERUM_PRESETS.each      { |p| Preset.create!(p.merge(plugin: serum)) }      if serum
GUITAR_RIG_PRESETS.each { |p| Preset.create!(p.merge(plugin: guitar_rig)) } if guitar_rig
puts "  #{Preset.count} presets created."

puts "Done."
